language: ruby

rvm:
  - "2.3.1"

env:
 - DB=pgsql

services:
 - postgresql

script:
 - RAILS_ENV=test bundle exec rake db:migrate
 - bundle exec rake db:test:prepare
 - bundle exec rake

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database side_work_test;' -U postgres